package com.sectrend.buildscan.buildTools.scanner.model;

import java.util.Arrays;
import java.util.List;

/**
 * @Description
 * @Author yang.zhang
 * @Date 2024/1/2 9:39
 **/
public class ExtFingerprintScanConstants {
    Integer WFP_CORE_DEFAULT_THREAD = 5;
    Integer WFP_MAX_DEFAULT_THREAD = 10;
    Integer WFP_QUEUE_DEFAULT_CAPACITY = 100;
    Integer FINGERPRINT_UPLOAD_DEFAULT_BUFFER_SIZE = 256 * 1024;
    Integer OUTPUT_FAILED_TO_DOWNLOAD_FILE_COUNT = 100;

    String FILE_PATH_AND_HASH_CONNECTOR = "|";

    String FINGERPRINT_FILE_PATH_SEPARATOR = "/";

    String WFP_CORE_THREAD_KEY = "wfpCoreThread";

    String WFP_MAX_THREAD_KEY = "wfpMaxThread";

    String WFP_QUEUE_CAPACITY_KEY = "wfpQueueCapacity";

    String WFP_FILE_PATH_PREFIX = "file=";

    String JAR_FILE_EXTENSION = ".jar";

    String AAR_FILE_EXTENSION = ".aar";

    String OBJECT_NAME_FINGERPRINT = "fingerprint";

    String FINGERPRINT_FILE = "fingerprint_file";

    String FOLDER_SCAN_RESULT_FILE = "folderScanResult";

    String DIRECTORY_SCAN_RESULT_FILE = "directoryScanResult";

    String FOLDER_SCAN_RAW_RESULT_FILE = "folderScanRawResult.json";

    String DIRECTORY_FILE = "directory_fingerprint";

    String DIRECTORY_FINGERPRINT_FILE = "directory_fingerprint_file";

    String SOURCE_FINGERPRINT_FILE = "source_fingerprint_file";

    String FILE_SIZE_INFO = "file_size_info";

    String DELETED_FILES = "deleted_files";

    String NEW_AND_OLD_FINGERPRINT_MAPPING_FILE = "new_and_old_fingerprint_mapping_file";

    String KEY_PROJECT_SIZE_CALC_RESULT = "projectSizeCalcResult";

    String KEY_SCAN_USED_CAPACITY = "scanUsedCapacity";

    String WFP_LINE_RESULT = "wfpLineResult";

    String DIR_COMPARE_RESULT = "dirCompareResult";

    String FINGERPRINT_UPLOAD_BUFFER_SIZE = "fingerprintUploadBufferSize";

    String KEY_FINGERPRINT_GENERATION_SUB_TASK_SUCCESS_COUNT = "fingerprintGenerationSubTaskSuccessCount";

    String KEY_SCAN_STARTED_FLAG = "scanStartedFlag";

    String RECORD_DOWNLOADED_FILE_LIST = "recordDownloadedFileList";

    // 指纹文件要过滤掉的文件哈希值
    public static List<String> WFP_FILTER_FILE_HASH = Arrays.asList("0962291d6d367570bee5454721c17e11", "0f3006e20d30987b4fdd49c4a0adf342",
            "1244d3f2f28ecc6619157927aca95200", "2c58c801945b382ae168280eb80092b6",
            "327711a461a30ba31b918dc30a08ccae", "34ea47c60598f102697b4476b742f873",
            "375ddea382b6c56a7be2a967a20e0ab5", "3a55d95595a6f9e37dee53826b4daff2",
            "41876349cb12d6db992f1309f22df3f0", "42679f369206e3da1495ed8abf870cee",
            "443141a90f711430c1423855b273d2fa", "448c34a56d699c29117adc64c43affeb",
            "4a010b8264c9873452f055748133bb29", "54542dc54ebae0de4502a1319144538f",
            "72b0b8f922dc7f125c7aaed79f9d274a", "76cdb2bad9582d23c1f6f4d868218d6c",
            "80cb6cf2fe634fe0eaa8a32ce59bee73", "8111d301bde6dd4875417be5a9d12fd5",
            "86bc7f6bce545c75611d599acec5d494", "8f68037672effa2917b28650c7cbce1f",
            "93fb6cea8fc778af4030da1ceb7d4f60", "96ba0a444d087ae06f32319ca4f0a3e4",
            "97471e1a0beb9650905b574145ae4638", "9c64fec71a86faf860632aca64da7ef1",
            "a670520d9d36833b3e28d1e4b73cbe22", "abd1ac26aaea8b55ff1eefd6caca1e55",
            "b03f60eea43420aef3ecd1f96c455d97", "c9eb740112b98a4ffa4b6e8965caa81f",
            "d3e3748e06793d488ae92138dd974ef8", "de8ffdb592ab304b14832467aef77cb3",
            "e24114dd1624e26140c00c0d49ba9837", "e909b282419acd3b63f5fb68db3bbc9b",
            "f10f4e8a24a6f29f60f73caf7341f44d", "fdb446fc9fbdb44dd511ce3d449504b0");

    // 指纹文件做精确目录前要过滤掉的后缀（忽略大小写）
    public static List<String> WFP_DIRECTORY_FILTER_POSTFIX = Arrays.asList(".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9", ".ac", ".adoc", ".am", ".asc",
            ".asciidoc", ".bmp", ".build", ".cfg", ".chm", ".class", ".cmake", ".cnf", ".conf",
            ".config", ".contributors", ".copying", ".crt", ".csproj", ".css", ".csv", ".cvsignore",
            ".dat", ".data", ".db", ".doc", ".ds_store", ".dtd", ".dts", ".dtsi", ".dump", ".eot",
            ".eps", ".geojson", ".gdoc", ".gif", ".gitignore", ".glif", ".gmo", ".gradle", ".guess",
            ".hex", ".htm", ".html", ".ico", ".in", ".inc", ".info", ".ini", ".ipynb", ".jpeg", ".jpg",
            ".json", ".jsonld", ".log", ".m4", ".map", ".markdown", ".md", ".md5", ".meta", ".mk",
            ".mxml", ".o", ".otf", ".out", ".pbtxt", ".pdf", ".pem", ".phtml", ".plist", ".png", ".po",
            ".ppt", ".prefs", ".properties", ".pyc", ".qdoc", ".result", ".rgb", ".rst", ".rtf",
            ".scss", ".sha", ".sha1", ".sha2", ".sha256", ".sln", ".spec", ".sql", ".sub", ".svg",
            ".svn-base", ".tab", ".template", ".test", ".tex", ".tiff", ".toml", ".ttf", ".txt",
            ".utf-8", ".vim", ".wav", ".whl", ".woff", ".xht", ".xhtml", ".xls", ".xml", ".xpm",
            ".xsd", ".xul", ".yaml", ".yml", ".LAS", ".adk", ".asc", ".cif", ".cli", ".cosmo",
            ".deploy", ".dfm", ".dmm", ".fa", ".fasta", ".fcb", ".flm", ".fna", ".gbr", ".gen", ".gro",
            ".hgtags", ".hh", ".ihex", ".kp", ".mpx", ".pdb", ".poly", ".prn", ".ps", ".ref", ".resx",
            ".smp", ".stg", ".tfa", ".tsv", ".vcf", ".vhd", ".xy", ".xyz", "-doc", "changelog",
            "config", "copying", "copying.lib", "license", "license.md", "license.txt", "licenses",
            "makefile", "notice", "readme", "swiftdoc", "texidoc", "todo", "version");

    // 做精确目录前要指定文件大小最大值（单位 byte）
    public static int WFP_DIRECTORY_MAX_FILE_SIZE = 4194304;

    // 做精确目录前要指定文件路径的二进制最大长度（转二进制用utf8编码）
    int WFP_DIRECTORY_FILE_PATH_MAX_BINARY_LENGTH = 4096;

    // 做精确目录前要过滤的文件路径的节点
    public static List<String> WFP_DIRECTORY_FILTER_FILE_PATH_NODE = Arrays.asList(".svn", ".hg", ".bzr", ".cvs", ".git", ".", "..", ".repo");

    // 计算代码行需要过滤行数的文件后缀
    public static List<String> EXCLUDE_LINE_COUNT_SUFFIX_LIST = Arrays.asList(".jar", ".war", ".zip", ".gz", ".tar", ".aar", ".apk", ".egg", ".tgz", ".rpm",
            ".whl", ".tar.bz2", ".tar.xz", ".xz", ".bz2", ".cpio", ".gradle", ".xml", ".json");

    // 计算代码行需要过滤行数的文件名
    public static List<String> EXCLUDE_FILE_NAME_LIST = Arrays.asList("Pipfile", "requirements.txt", "control");

    // 计算代码行需要过滤行数的项目许可证文件名
    public static List<String> EXCLUDE_LICENSE_NAME_LIST = Arrays.asList("license", "licenses", "licence", "licences");

    // 文件后缀白名单
    public static List<String> CODE_SUFFIX_WHITE_LIST = Arrays.asList(
            "hxx",
            "airpackage",
            "bps",
            "eslintignore",
            "pyz",
            "npmrc",
            "completion",
            "pom",
            "process",
            "gsc",
            "ux",
            "mailmap",
            "cql",
            "nc",
            "lean",
            "der",
            "dxw",
            "mdb",
            "vpi",
            "br",
            "drm",
            "resource",
            "pec",
            "deploy",
            "pc",
            "pony",
            "cocoascript",
            "dbc",
            "vimrc",
            "pwn",
            "recipe",
            "marko",
            "motd",
            "babelrc",
            "btl",
            "fnt",
            "opk",
            "desktop",
            "mtn",
            "doctree",
            "apkg",
            "eb",
            "dsidx",
            "xdxf",
            "ri",
            "yymps",
            "blp",
            "sorbet",
            "edn",
            "xbf",
            "zul",
            "m3u8",
            "acl",
            "hat",
            "ssp",
            "sys",
            "chromium",
            "cwl",
            "shader",
            "seed",
            "stub",
            "chromiumos",
            "vsl",
            "reg",
            "ovpn",
            "php3",
            "pickle",
            "filter",
            "mys",
            "fmt",
            "rmskin",
            "table",
            "cfgdef",
            "dtbo",
            "bst",
            "srt",
            "nf",
            "pgm",
            "sparql",
            "dbf",
            "mc",
            "bats",
            "learn",
            "toit",
            "settings",
            "bos",
            "cdi",
            "ext",
            "sip",
            "graffle",
            "lrp",
            "ser",
            "profile",
            "svgz",
            "vmdk",
            "semantics",
            "graphqls",
            "pbf",
            "jinja",
            "ly",
            "sgml",
            "dol",
            "nar",
            "prop",
            "asar",
            "spk",
            "bpmn",
            "rbxmx",
            "jax",
            "smx",
            "bsl",
            "old",
            "cnb",
            "cer",
            "ttinclude",
            "launch",
            "x",
            "xlsm",
            "hack",
            "bsh",
            "accesswidener",
            "ods",
            "gzip",
            "pk3",
            "jade",
            "board",
            "item",
            "f0",
            "abap",
            "upl",
            "atlas",
            "mft",
            "ova",
            "dockerfile",
            "lzma",
            "quickdic",
            "hh",
            "args",
            "tt",
            "aut",
            "files",
            "p",
            "nsh",
            "stylelintrc",
            "dhall",
            "bpmn2",
            "pa",
            "link",
            "blueprint",
            "symbols",
            "glb",
            "bs",
            "workbook",
            "pyo",
            "xlf",
            "ls",
            "classdata",
            "aab",
            "bb",
            "vcvplugin",
            "gta",
            "swp",
            "dnn",
            "fusion",
            "pub",
            "rdf",
            "snap",
            "bdic",
            "xnb",
            "brs",
            "rpy",
            "cov",
            "apib",
            "handler2s",
            "kml",
            "cue",
            "xsh",
            "aia",
            "p3t",
            "prg",
            "squashfs",
            "dict",
            "htaccess",
            "script",
            "linux",
            "pt",
            "dex",
            "idl",
            "xslt",
            "mu",
            "kjsm",
            "wxc",
            "rbxm",
            "mid",
            "odp",
            "trx",
            "asi",
            "afm",
            "app",
            "oxt",
            "sysprop",
            "mcpack",
            "bas",
            "g4",
            "zbud6",
            "sha256sum",
            "dmn",
            "ecsv",
            "jfif",
            "fxml",
            "gui",
            "pd",
            "smali",
            "xjb",
            "qmod",
            "mdl",
            "adm",
            "ssurl",
            "xsp",
            "name",
            "robot",
            "bsr",
            "psm1",
            "r",
            "fidl",
            "jsonnet",
            "vtl",
            "mp4",
            "astro",
            "skin",
            "dic",
            "pdn",
            "mapping",
            "p12",
            "tga",
            "scad",
            "gstz",
            "qm",
            "zig",
            "inf",
            "sch",
            "pot",
            "cxx",
            "gpg",
            "hjson",
            "vscodeignore",
            "xmind",
            "im4p",
            "cf",
            "txz",
            "zs",
            "e",
            "tid",
            "ent",
            "gem",
            "3dsx",
            "jsonschema",
            "eslintrc",
            "pkl",
            "nii",
            "asp",
            "webm",
            "rnc",
            "m3u",
            "pmml",
            "traineddata",
            "bal",
            "flf",
            "mpk",
            "sha512",
            "avsc",
            "fits",
            "tld",
            "ipa",
            "raml",
            "params",
            "ycp",
            "iml",
            "sl",
            "jnilib",
            "jpl",
            "sv",
            "tvtp",
            "pth",
            "f",
            "tx",
            "sk",
            "git",
            "conllu",
            "iso",
            "anm2",
            "google",
            "mkdn",
            "dpkg",
            "vbs",
            "jsonc",
            "scm",
            "ss",
            "pext",
            "prov",
            "pyw",
            "run",
            "fsh",
            "cia",
            "puml",
            "odt",
            "text",
            "cshtml",
            "mat",
            "hgignore",
            "pan",
            "es6",
            "npy",
            "obj",
            "raw",
            "uc",
            "cnxml",
            "sls",
            "dbg",
            "dar",
            "bak",
            "cssm",
            "nix",
            "sum",
            "xaml",
            "lngx",
            "tfvars",
            "make",
            "drawio",
            "mpy",
            "msg",
            "cljc",
            "nbm",
            "ddl",
            "wasm",
            "externals",
            "wdl",
            "xtend",
            "sas",
            "project",
            "vi",
            "pure",
            "nds",
            "sqlite",
            "env",
            "ktx",
            "es",
            "cache",
            "jelly",
            "ml",
            "jd",
            "components",
            "yamllint",
            "ax",
            "changes",
            "tbz",
            "nut",
            "liquid",
            "dependencies",
            "nbt",
            "lgc",
            "gs",
            "gotmpl",
            "parquet",
            "bsi",
            "pkey",
            "npz",
            "elf",
            "h5",
            "mcmeta",
            "file",
            "spv",
            "prc",
            "install",
            "pddl",
            "debug",
            "glsl",
            "arturo",
            "swf",
            "sign",
            "interceptors",
            "sketch",
            "trace",
            "hcl",
            "feature",
            "types",
            "stl",
            "enc",
            "gml",
            "n4jsd",
            "ics",
            "ldif",
            "pug",
            "psmdcp",
            "gemspec",
            "rsc",
            "ai",
            "handlebars",
            "cabal",
            "zstd",
            "rkt",
            "zsh",
            "wsdl",
            "rules",
            "fish",
            "pde",
            "sss",
            "RecordeWorkspaces",
            "rc",
            "xcf",
            "dtb",
            "cfc",
            "graphql",
            "sqf",
            "hash",
            "rar",
            "page",
            "car",
            "alfredworkflow",
            "cljs",
            "pck",
            "scssc",
            "asset",
            "android",
            "qml",
            "cl",
            "thrift",
            "vb",
            "pyd",
            "frag",
            "provides",
            "7z",
            "njk",
            "lombok",
            "strings",
            "au3",
            "psd",
            "flat",
            "org",
            "f90",
            "jsf",
            "nib",
            "efi",
            "pack",
            "sc",
            "lst",
            "theme",
            "phar",
            "wsdd",
            "sp",
            "parkobj",
            "ttl",
            "minisig",
            "bash",
            "plt",
            "mobi",
            "fs",
            "bz2",
            "bp",
            "v",
            "toc",
            "vala",
            "pp",
            "iss",
            "cmd",
            "drl",
            "uasset",
            "asm",
            "zsync",
            "pcss",
            "tmpl",
            "tmod",
            "beam",
            "crx",
            "pro",
            "bloom",
            "gitmodules",
            "ko",
            "dds",
            "pkg",
            "lisp",
            "cc",
            "tif",
            "pptx",
            "yang",
            "aar",
            "phpt",
            "lng",
            "mod",
            "list",
            "sty",
            "cson",
            "sample",
            "db",
            "bib",
            "cls",
            "re",
            "war",
            "res",
            "rego",
            "cat",
            "pas",
            "mdp",
            "epub",
            "bundle",
            "pkgs",
            "dmg",
            "podspec",
            "ttc",
            "erb",
            "xpi",
            "xsl",
            "flow",
            "uf2",
            "purs",
            "jks",
            "pb",
            "ahk",
            "dgst",
            "te",
            "gd",
            "tcl",
            "mustache",
            "hx",
            "t",
            "icns",
            "unitypackage",
            "semanticdb",
            "as",
            "mcfunction",
            "styl",
            "unityweb",
            "rpt",
            "msi",
            "ino",
            "xsb",
            "snupkg",
            "bcmap",
            "ejs",
            "debuginfo",
            "cjs",
            "sass",
            "elm",
            "xz",
            "lib",
            "nim",
            "hbs",
            "cr",
            "img",
            "mo",
            "xlsx",
            "vm",
            "docx",
            "nir",
            "vpk",
            "pl",
            "knm",
            "vsix",
            "mdx",
            "torrent",
            "pyi",
            "zst",
            "twig",
            "a",
            "pm",
            "tpl",
            "bat",
            "idx",
            "sol",
            "ftl",
            "dylib",
            "webp",
            "el",
            "svelte",
            "erl",
            "helmignore",
            "j2",
            "manifest",
            "jsp",
            "catz",
            "rds",
            "sha256sums",
            "buildinfo",
            "udeb",
            "tar",
            "d",
            "lang",
            "gitattributes",
            "npmignore",
            "m",
            "apk",
            "ddeb",
            "hpp",
            "mp3",
            "sym",
            "hs",
            "tgz",
            "lock",
            "cpp",
            "factories",
            "st",
            "diff",
            "sig",
            "jsx",
            "s",
            "proto",
            "bin",
            "coffee",
            "module",
            "clj",
            "lz",
            "zip",
            "gz",
            "less",
            "so",
            "pak",
            "ipk",
            "dsc",
            "ogg",
            "groovy",
            "mjs",
            "ps1",
            "tsx",
            "patch",
            "dart",
            "node",
            "tf",
            "c",
            "vue",
            "blockmap",
            "jl",
            "rpm",
            "lua",
            "tasty",
            "sjsir",
            "nuspec",
            "woff2",
            "swift",
            "h",
            "rs",
            "exe",
            "sh",
            "dll",
            "kt",
            "nupkg",
            "cs",
            "rb",
            "go",
            "scala",
            "jar",
            "deb",
            "php",
            "ts",
            "py",
            "java",
            "js");

}
